name: Build-x86_64-Windows_generic
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows-2019
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4.1.1
     
      - name: Clone the tensorflow library & checkout to latest tag
        run: git clone https://github.com/tensorflow/tensorflow; cd tensorflow; git fetch --tags; $tag = git describe --tags (git rev-list --tags --max-count=1); git checkout $tag; $tag | Out-File -FilePath ../tag.txt -Encoding utf8
     
      - name: Build the tensorflow lite library using Bazel
        working-directory: ./tensorflow
        run: bazel build //tensorflow/lite:libtensorflowlite.so -c opt --copt=/O2 --copt=/arch:AVX2 --copt=/D_XNN_ENABLE_AVX512AMX=0 --copt=/D_XNN_ENABLE_AVX512F16=0 --cxxopt=/D_XNN_ENABLE_AVX512AMX=0 --cxxopt=/D_XNN_ENABLE_AVX512F16=0 --copt=/D_RUY_PLATFORM_AVX512=0 --copt=/std:c++20
     
      - name: Assemble package
        working-directory: ./tensorflow
        run: New-Item -ItemType Directory -Force -Path ../package/lib, ../package/inc/tensorflow/lite

      - name: Copy include files from flatbuffers into new package
        working-directory: ./tensorflow
        run: Copy-Item -Path bazel-tensorflow/external/flatbuffers/include/* -Destination ../package/inc -Recurse

      - name: Copy include files from tensorflow lite into new package
        working-directory: ./tensorflow
        run: Copy-Item -Path tensorflow/lite/* -Destination ../package/inc/tensorflow/lite -Recurse

      - name: Copy dynamic library file (.dll) from bazel build dir to new package
        working-directory: ./tensorflow
        run: Copy-Item -Path bazel-out/k8-opt/bin/tensorflow/lite/libtensorflowlite.dll -Destination ../package/lib/

      - name: Copy template CMakeLists.txt to new package
        run: Copy-Item -Path cmake/CMakeLists.txt -Destination package/

      - name: Remove other language bindings/examples/docs from the include directory
        run: Remove-Item -Recurse -Force package/inc/tensorflow/lite/testing, package/inc/tensorflow/lite/java, package/inc/tensorflow/lite/ios, package/inc/tensorflow/lite/objc, package/inc/tensorflow/lite/python, package/inc/tensorflow/lite/tools, package/inc/tensorflow/lite/swift, package/inc/tensorflow/lite/examples

      - name: Strip the tensorflow lite include dir (so that it only contains header files)
        run: Get-ChildItem -Path package/inc/tensorflow -Recurse -File | Where-Object { $_.Extension -notin ".h", ".hpp" } | Remove-Item -Force

      - name: Remove empty folders
        run: Get-ChildItem -Path package/inc/tensorflow -Recurse -Directory | Where-Object { $_.GetFileSystemInfos().Count -eq 0 } | Remove-Item -Force

      - name: Zip it up
        run: Compress-Archive -Path package/* -DestinationPath ../tensorflow_windows_vs19_avx2_x86_64.zip

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload (Get-Content tag.txt) tensorflow_windows_vs19_avx2_x86_64.zip
